# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  init:
    desc: Install dependencies
    cmds:
      - uv sync

  # -- yolo tasks

  train:
    desc: Train the YOLO model
    cmds:
      - uv run src/train.py

  
  # -- Git-related tasks
  git-push:
    desc: push changes to the remote repository
    cmds:
      - git push origin --all
      - git push --force origin --tags
      - git push wd --all
      - git push --force wd --tags
      